export const ATPROTO_GRANULAR_SCOPE = [
  'atproto',
  'blob:*/*',
  'repo:app.bsky.feed.post?action=create',
  'repo:coop.hypha.spores.content.image',
  'repo:coop.hypha.spores.content.text',
  'repo:coop.hypha.spores.item.specialSpore',
  'repo:coop.hypha.spores.site.config',
  'repo:coop.hypha.spores.site.layout',
  'repo:coop.hypha.spores.site.profile',
  'repo:coop.hypha.spores.site.section',
  'repo:coop.hypha.spores.social.flower',
  'repo:coop.hypha.spores.social.takenFlower',
  'repo:ing.dasl.masl',
  'repo:garden.spores.content.image',
  'repo:garden.spores.content.text',
  'repo:garden.spores.item.specialSpore',
  'repo:garden.spores.site.config',
  'repo:garden.spores.site.layout',
  'repo:garden.spores.site.profile',
  'repo:garden.spores.site.sections',
  'repo:garden.spores.site.section',
  'repo:garden.spores.social.flower',
  'repo:garden.spores.social.takenFlower',
].join(' ');
